# .gitlab-ci.yml

# Specify the image to use for the job
image: node:18.17.1

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy    # New stage for deployment

services:
  - docker:dind

  # Job to build and push Docker image
docker-build:
  stage: build
  image: docker:latest
  script:
    - echo "Logging in to GitLab Docker registry..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "Building Docker image..."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - echo "Pushing Docker image to GitLab registry..."
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - main    # Run this job only on pushes to the main branch
    - develop


# Job to run tests
unit-test-job:
  stage: test  
  script:
    - npm install
    - npm run test:unit